/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  safelist: [
    'space-y-8',
    'space-y-4',
    'space-y-6',
    'space-y-2',
    'text-4xl',
    'text-3xl',
    'text-2xl',
    'text-lg',
    'font-bold',
    'font-semibold',
    'mb-6',
    'mb-4',
    'mb-3',
    'leading-relaxed',
    'h-[600px]',
    'h-[500px]',
    'object-cover',
    'rounded-lg',
    'border-2',
    'border-gray-600',
    'border-gray-700',
    'shadow-lg',
    'bg-gray-700',
    'p-6',
    'pt-8',
    'text-yellow-400',
    'text-blue-400',
    'hover:text-blue-300',
    'hover:text-blue-600',
    'hover:bg-blue-600',
    'bg-blue-500',
    'underline',
    'list-disc',
    'list-inside',
    'flex',
    'items-center',
    'justify-center',
    'transition',
    'duration-300',
    'py-3',
    'px-6',
    'space-x-2',
    'w-full',
    'h-6',
    'w-6'
  ],
  theme: {
    extend: {
      fontFamily: {
        'pacifico': ['Pacifico', 'cursive'], // Add the font as a custom family
      },
    },
  },
  plugins: [],
}

